# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: post_views.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10post_views.proto\"\"\n\x0fPostViewRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\x05\"<\n\x10PostViewResponse\x12\x0f\n\x07post_id\x18\x01 \x01(\x05\x12\x17\n\x0fpost_view_count\x18\x02 \x01(\x05\x32\xf0\x01\n\x11PostViewAnalytics\x12\x33\n\x0cGetViewCount\x12\x10.PostViewRequest\x1a\x11.PostViewResponse\x12\x36\n\x0f\x43reateViewCount\x12\x10.PostViewRequest\x1a\x11.PostViewResponse\x12\x36\n\x0fUpdateViewCount\x12\x10.PostViewRequest\x1a\x11.PostViewResponse\x12\x36\n\x0f\x44\x65leteViewCount\x12\x10.PostViewRequest\x1a\x11.PostViewResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'post_views_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POSTVIEWREQUEST']._serialized_start=20
  _globals['_POSTVIEWREQUEST']._serialized_end=54
  _globals['_POSTVIEWRESPONSE']._serialized_start=56
  _globals['_POSTVIEWRESPONSE']._serialized_end=116
  _globals['_POSTVIEWANALYTICS']._serialized_start=119
  _globals['_POSTVIEWANALYTICS']._serialized_end=359
# @@protoc_insertion_point(module_scope)
