# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc

from . import post_views_pb2 as post__views__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in post_views_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class PostViewAnalyticsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetViewCount = channel.unary_unary(
                '/PostViewAnalytics/GetViewCount',
                request_serializer=post__views__pb2.PostViewRequest.SerializeToString,
                response_deserializer=post__views__pb2.PostViewResponse.FromString,
                _registered_method=True)
        self.CreateViewCount = channel.unary_unary(
                '/PostViewAnalytics/CreateViewCount',
                request_serializer=post__views__pb2.PostViewRequest.SerializeToString,
                response_deserializer=post__views__pb2.PostViewResponse.FromString,
                _registered_method=True)
        self.UpdateViewCount = channel.unary_unary(
                '/PostViewAnalytics/UpdateViewCount',
                request_serializer=post__views__pb2.PostViewRequest.SerializeToString,
                response_deserializer=post__views__pb2.PostViewResponse.FromString,
                _registered_method=True)
        self.DeleteViewCount = channel.unary_unary(
                '/PostViewAnalytics/DeleteViewCount',
                request_serializer=post__views__pb2.PostViewRequest.SerializeToString,
                response_deserializer=post__views__pb2.PostViewResponse.FromString,
                _registered_method=True)


class PostViewAnalyticsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetViewCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateViewCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateViewCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteViewCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PostViewAnalyticsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetViewCount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetViewCount,
                    request_deserializer=post__views__pb2.PostViewRequest.FromString,
                    response_serializer=post__views__pb2.PostViewResponse.SerializeToString,
            ),
            'CreateViewCount': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateViewCount,
                    request_deserializer=post__views__pb2.PostViewRequest.FromString,
                    response_serializer=post__views__pb2.PostViewResponse.SerializeToString,
            ),
            'UpdateViewCount': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateViewCount,
                    request_deserializer=post__views__pb2.PostViewRequest.FromString,
                    response_serializer=post__views__pb2.PostViewResponse.SerializeToString,
            ),
            'DeleteViewCount': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteViewCount,
                    request_deserializer=post__views__pb2.PostViewRequest.FromString,
                    response_serializer=post__views__pb2.PostViewResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PostViewAnalytics', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PostViewAnalytics', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PostViewAnalytics(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetViewCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PostViewAnalytics/GetViewCount',
            post__views__pb2.PostViewRequest.SerializeToString,
            post__views__pb2.PostViewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateViewCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PostViewAnalytics/CreateViewCount',
            post__views__pb2.PostViewRequest.SerializeToString,
            post__views__pb2.PostViewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateViewCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PostViewAnalytics/UpdateViewCount',
            post__views__pb2.PostViewRequest.SerializeToString,
            post__views__pb2.PostViewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteViewCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PostViewAnalytics/DeleteViewCount',
            post__views__pb2.PostViewRequest.SerializeToString,
            post__views__pb2.PostViewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
