###
POST {{base_url}}/auth/
Content-Type: application/json

{"email": "a.abharya@gmail.com",
  "password": "123456"
}
###

POST {{base_url}}/auth/login/
Content-Type: application/json

{"email": "a.abharya@gmail.com",
  "password": "123456"
}
###

GET {{base_url}}/users/me/
Accept: application/json
Authorization: Bearer {{token}}

###
DELETE {{base_url}}/users/me/
Accept: application/json
Authorization: Bearer {{token}}
###

###
GET {{base_url}}/users/me/followings/
Accept: application/json
Authorization: Bearer {{token}}
###

###
GET {{base_url}}/users/me/followers/
Accept: application/json
Authorization: Bearer {{token}}
###

DELETE {{base_url}}/users/me/followers/1/
Accept: application/json
Authorization: Bearer {{token}}
###

###
POST {{base_url}}/users/me/followings/
Accept: application/json
Authorization: Bearer {{token}}

{"user_id": 1
}
###

DELETE {{base_url}}/users/me/followings/2/
Accept: application/json
Authorization: Bearer {{token}}
###

POST {{base_url}}/posts/
Content-Type: application/json
Authorization: Bearer {{token}}

{"content": "this is a 2 test message"
}
###

GET {{base_url}}/posts/
Accept: application/json
Authorization: Bearer {{token}}

###
PATCH {{base_url}}/posts/2/
Content-Type: application/json
Authorization: Bearer {{token}}

{"content": "this is a updated 1515 message"
}

###
DELETE {{base_url}}/posts/2/
Accept: application/json
Authorization: Bearer {{token}}
###
