###
POST {{base_url}}/auth/
Content-Type: application/json

{"email": "a.abharya@gmail.com",
  "password": "123456"
}
###

POST {{base_url}}/auth/login/
Content-Type: application/json

{"email": "a.abharya@gmail.com",
  "password": "123456"
}
###

GET {{base_url}}/users/profile/
Accept: application/json
Authorization: Bearer {{token}}

###
DELETE {{base_url}}/profile/
###

###
POST {{base_url}}/posts/
Content-Type: application/json
Authorization: Bearer {{token}}

{"content": "this is a 3 test message"
}
###

GET {{base_url}}/posts/
Accept: application/json
Authorization: Bearer {{token}}

###
PATCH {{base_url}}/posts/2/
Content-Type: application/json
Authorization: Bearer {{token}}

{"content": "this is a updated 2 message"
}

###
DELETE {{base_url}}/posts/4/
Accept: application/json
Authorization: Bearer {{token}}
###
